### ISSUE TITLE
Hoffstadt Notes & TODOs

### ISSUE THREAD

**Issue by hoffstadt** [PilotLightTech/pilotlight#9]
### Core
* [ ] store command line arguments in data registry

### Graphics
* [ ] stencil buffer support #7
* [ ] MSAA support #6
* [ ] handle descriptor management/reuse #5 
* [ ] expose queues #4
* [ ] move 3D debug API to separate extension #3 
* [ ] investigate SPIR-V cross support
* [ ] investigate glslc library inclusion
* [ ] add support for indirect buffers #8
* [ ] create standalone examples
* [ ] add features querying
* [ ] add more init options

### ECS
* [ ] Layer component
* [ ] Light component
* [ ] Imposter component
* [ ] Humanoid component
* [ ] Material component completion
* [ ] Object component completion

### Reference Renderer
* [ ] Decide on bindless/traditional binding models
* [ ] Shader hot reload
* [ ] Debug modes
* [ ] Morphing
* [ ] Add transparency pass
* [ ] Shadows
* [ ] Better test scene
* [ ] Decals
* [ ] Picking & Highlighting

**Comment by hoffstadt** [comment]
Saving for gizmo work:

```c
        // outlines
        const uint32_t uOutlineDrawableCount = pl_sb_size(ptScene->sbtOutlineDrawables);
        const plVec4 tOutlineColor0 = (plVec4){1.0f, 1.0f, 0.0f, 0.45f};

        {
            plDrawCapsuleDesc tDrawDesc = {0};
            gptDraw->fill_capsule_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){-5.0f, 0.0f, -1.0f};
            tDrawDesc.tTipPos = (plVec3){-5.0f, 3.0f, -1.0f};
            gptDraw->add_3d_capsule_ex(ptView->pt3DSelectionDrawList, &tDrawDesc);
        }

        {
            plDrawCapsuleDesc tDrawDesc = {0};
            gptDraw->fill_capsule_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){-3.0f, 0.0f, -1.0f};
            tDrawDesc.tTipPos = (plVec3){-3.0f, 3.0f, -1.0f};
            tDrawDesc.fTipRadius = 0.2f;
            gptDraw->add_3d_capsule_ex(ptView->pt3DSelectionDrawList, &tDrawDesc);
        }

        {
            plDrawCylinderDesc tDrawDesc = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){-1.0f, 0.0f, -1.0f};
            tDrawDesc.tTipPos = (plVec3){-1.0f, 3.0f, -1.0f};
            gptDraw->add_3d_cylinder_ex(ptView->pt3DSelectionDrawList, &tDrawDesc);
        }

        {
            plDrawCylinderDesc tDrawDesc = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){-1.0f, 0.0f, -3.0f};
            tDrawDesc.tTipPos = (plVec3){-1.0f, 3.0f, -3.0f};
            tDrawDesc.tColor = tOutlineColor0;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DDrawList, &tDrawDesc);
        }

        {
            plDrawSphereDesc tDrawDesc = {0};
            gptDraw->fill_sphere_desc_default(&tDrawDesc);
            tDrawDesc.tCenter = (plVec3){1.0f, 1.0f, -1.0f};
            gptDraw->add_3d_sphere_ex(ptView->pt3DSelectionDrawList, &tDrawDesc);
        }

        {
            plDrawSphereDesc tDrawDesc = {0};
            gptDraw->fill_sphere_desc_default(&tDrawDesc);
            tDrawDesc.tCenter = (plVec3){1.0f, 1.0f, -3.0f};
            tDrawDesc.tColor = tOutlineColor0;
            gptDraw->add_3d_sphere_filled_ex(ptView->pt3DDrawList, &tDrawDesc);
        }

        {
            plDrawConeDesc tDrawDesc = {0};
            gptDraw->fill_cone_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){3.0f, 0.0f, -1.0f};
            tDrawDesc.tTipPos = (plVec3){3.0f, 3.0f, -1.0f};
            gptDraw->add_3d_cone_ex(ptView->pt3DSelectionDrawList, &tDrawDesc);
        }

        {
            plDrawConeDesc tDrawDesc = {0};
            gptDraw->fill_cone_desc_default(&tDrawDesc);
            tDrawDesc.tBasePos = (plVec3){3.0f, 0.0f, -3.0f};
            tDrawDesc.tTipPos = (plVec3){3.0f, 3.0f, -3.0f};
            tDrawDesc.tColor = tOutlineColor0;
            gptDraw->add_3d_cone_filled_ex(ptView->pt3DDrawList, &tDrawDesc);
        }

        // translation gizmo
        {
            const plVec3 tOrigin = {0.0f, 0.0f, 0.0f};
            const float fAxisRadius  = 0.025f;
            const float fArrowRadius = 0.05f;
            const float fArrowLength = 0.2f;
            const float fLength = 1.0f;

            // x arrow head
            plDrawConeDesc tDrawDesc0 = {0};
            gptDraw->fill_cone_desc_default(&tDrawDesc0);
            tDrawDesc0.tColor = (plVec4){1.0f, 0.0f, 0.0f, 1.0f};
            tDrawDesc0.tBasePos = (plVec3){tOrigin.x + fLength - fArrowLength, tOrigin.y, tOrigin.z};
            tDrawDesc0.tTipPos = (plVec3){tOrigin.x + fLength, tOrigin.y, tOrigin.z};
            tDrawDesc0.fRadius = fArrowRadius;
            gptDraw->add_3d_cone_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc0);

            // y arrow head
            plDrawConeDesc tDrawDesc1 = {0};
            gptDraw->fill_cone_desc_default(&tDrawDesc1);
            tDrawDesc1.tColor = (plVec4){0.0f, 1.0f, 0.0f, 1.0f};
            tDrawDesc1.tBasePos = (plVec3){tOrigin.x, tOrigin.y + fLength - fArrowLength, tOrigin.z};
            tDrawDesc1.tTipPos = (plVec3){tOrigin.x, tOrigin.y + fLength, tOrigin.z};
            tDrawDesc1.fRadius = fArrowRadius;
            gptDraw->add_3d_cone_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc1);

            // z arrow head
            plDrawConeDesc tDrawDesc2 = {0};
            gptDraw->fill_cone_desc_default(&tDrawDesc2);
            tDrawDesc2.tColor = (plVec4){0.0f, 0.0f, 1.0f, 1.0f};
            tDrawDesc2.tBasePos = (plVec3){tOrigin.x, tOrigin.y, tOrigin.z + fLength - fArrowLength};
            tDrawDesc2.tTipPos = (plVec3){tOrigin.x, tOrigin.y, tOrigin.z + fLength};
            tDrawDesc2.fRadius = fArrowRadius;
            gptDraw->add_3d_cone_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc2);

            // x axis
            plDrawCylinderDesc tDrawDesc3 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc3);
            tDrawDesc3.tColor = (plVec4){1.0f, 0.0f, 0.0f, 1.0f};
            tDrawDesc3.tBasePos = tOrigin;
            tDrawDesc3.tTipPos = (plVec3){tOrigin.x + fLength - fArrowLength, tOrigin.y, tOrigin.z};
            tDrawDesc3.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc3);

            // y axis
            plDrawCylinderDesc tDrawDesc4 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc4);
            tDrawDesc4.tColor = (plVec4){0.0f, 1.0f, 0.0f, 1.0f};
            tDrawDesc4.tBasePos = tOrigin;
            tDrawDesc4.tTipPos = (plVec3){tOrigin.x, tOrigin.y + fLength - fArrowLength, tOrigin.z};
            tDrawDesc4.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc4);

            // z axis
            plDrawCylinderDesc tDrawDesc5 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc5);
            tDrawDesc5.tColor = (plVec4){0.0f, 0.0f, 1.0f, 1.0f};
            tDrawDesc5.tBasePos = tOrigin;
            tDrawDesc5.tTipPos = (plVec3){tOrigin.x, tOrigin.y, tOrigin.z + fLength - fArrowLength};
            tDrawDesc5.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc5);

            // origin
            gptDraw->add_3d_centered_box_filled(ptView->pt3DSelectionDrawList,
                tOrigin,
                fAxisRadius * 4,
                fAxisRadius * 4,
                fAxisRadius * 4,
                (plVec4){0.5f, 0.5f, 0.5f, 1.0f});

            // PLANES
            gptDraw->add_3d_plane_xy_filled(ptView->pt3DSelectionDrawList, (plVec3){tOrigin.x + fLength * 0.25f, tOrigin.y + fLength * 0.25f, tOrigin.z}, fLength * 0.25f, fLength * 0.25f, (plVec4){0.0f, 0.0f, 1.0f, 0.5f});
            gptDraw->add_3d_plane_yz_filled(ptView->pt3DSelectionDrawList, (plVec3){tOrigin.x, tOrigin.y + fLength * 0.25f, tOrigin.z + fLength * 0.25f}, fLength * 0.25f, fLength * 0.25f, (plVec4){1.0f, 0.0f, 0.0f, 0.5f});
            gptDraw->add_3d_plane_xz_filled(ptView->pt3DSelectionDrawList, (plVec3){tOrigin.x + fLength * 0.25f, tOrigin.y, tOrigin.z + fLength * 0.25f}, fLength * 0.25f, fLength * 0.25f, (plVec4){0.0f, 1.0f, 0.0f, 0.5f});
        }

        // gizmo
        {
            const plVec3 tOrigin = {3.0f, 0.0f, 0.0f};
            const float fAxisRadius  = 0.025f;
            const float fArrowRadius = 0.05f;
            const float fLength = 1.0f;

            // x axis
            plDrawCylinderDesc tDrawDesc3 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc3);
            tDrawDesc3.tColor = (plVec4){1.0f, 0.0f, 0.0f, 1.0f};
            tDrawDesc3.tBasePos = tOrigin;
            tDrawDesc3.tTipPos = (plVec3){tOrigin.x + fLength, tOrigin.y, tOrigin.z};
            tDrawDesc3.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc3);

            // y axis
            plDrawCylinderDesc tDrawDesc4 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc4);
            tDrawDesc4.tColor = (plVec4){0.0f, 1.0f, 0.0f, 1.0f};
            tDrawDesc4.tBasePos = tOrigin;
            tDrawDesc4.tTipPos = (plVec3){tOrigin.x, tOrigin.y + fLength, tOrigin.z};
            tDrawDesc4.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc4);

            // z axis
            plDrawCylinderDesc tDrawDesc5 = {0};
            gptDraw->fill_cylinder_desc_default(&tDrawDesc5);
            tDrawDesc5.tColor = (plVec4){0.0f, 0.0f, 1.0f, 1.0f};
            tDrawDesc5.tBasePos = tOrigin;
            tDrawDesc5.tTipPos = (plVec3){tOrigin.x, tOrigin.y, tOrigin.z + fLength};
            tDrawDesc5.fRadius = fAxisRadius;
            gptDraw->add_3d_cylinder_filled_ex(ptView->pt3DSelectionDrawList, &tDrawDesc5);

            // x end
            gptDraw->add_3d_centered_box_filled(ptView->pt3DSelectionDrawList,
                (plVec3){tOrigin.x + fLength, tOrigin.y, tOrigin.z},
                fAxisRadius * 4,
                fAxisRadius * 4,
                fAxisRadius * 4,
                (plVec4){1.0f, 0.0f, 0.0f, 1.0f});

            // y end
            gptDraw->add_3d_centered_box_filled(ptView->pt3DSelectionDrawList,
                (plVec3){tOrigin.x, tOrigin.y + fLength, tOrigin.z},
                fAxisRadius * 4,
                fAxisRadius * 4,
                fAxisRadius * 4,
                (plVec4){0.0f, 1.0f, 0.0f, 1.0f});

            // z end
            gptDraw->add_3d_centered_box_filled(ptView->pt3DSelectionDrawList,
                (plVec3){tOrigin.x, tOrigin.y, tOrigin.z + fLength},
                fAxisRadius * 4,
                fAxisRadius * 4,
                fAxisRadius * 4,
                (plVec4){0.0f, 0.0f, 1.0f, 1.0f});

            // origin
            gptDraw->add_3d_centered_box_filled(ptView->pt3DSelectionDrawList,
                tOrigin,
                fAxisRadius * 4,
                fAxisRadius * 4,
                fAxisRadius * 4,
                (plVec4){0.5f, 0.5f, 0.5f, 1.0f});

        }

        // rotation gizmo
        {
            const plVec3 tOrigin = {2.0f, 0.0f, 0.0f};
            const float fInnerRadius = 0.4f;
            const float fOuterRadius = 0.5f;
            gptDraw->add_3d_band_xz_filled(ptView->pt3DSelectionDrawList, tOrigin, fInnerRadius, fOuterRadius, (plVec4){0.0f, 1.0f, 0.0f, 1.0f}, 36);
            gptDraw->add_3d_band_xy_filled(ptView->pt3DSelectionDrawList, tOrigin, fInnerRadius, fOuterRadius, (plVec4){0.0f, 0.0f, 1.0f, 1.0f}, 36);
            gptDraw->add_3d_band_yz_filled(ptView->pt3DSelectionDrawList, tOrigin, fInnerRadius, fOuterRadius, (plVec4){1.0f, 0.0f, 0.0f, 1.0f}, 36);
        }
```
